# Generated by Django 5.1.1 on 2024-10-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_profile_learn_profile_teach_alter_profile_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="google_form_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Write a short sentence description about yourself",
                max_length=50,
                null=True,
                verbose_name="Description",
            ),
        ),
    ]
