# Generated by Django 4.2.16 on 2025-01-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_profile_google_form_url_alter_profile_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="google_form_url",
        ),
        migrations.AddField(
            model_name="profile",
            name="question",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
