# Generated by Django 4.2.16 on 2025-01-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_remove_profile_google_form_url_profile_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="learn",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="question",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="teach",
        ),
        migrations.AddField(
            model_name="profile",
            name="ACS_association",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ACS Association"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="area_of_interest",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Area of Interest"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="athletics",
            field=models.CharField(
                blank=True,
                help_text="Select your athletics interests, separated by commas.",
                max_length=200,
                null=True,
                verbose_name="Athletics",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="athletics_other",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Other Athletics"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="desired_role",
            field=models.CharField(
                blank=True,
                choices=[("mentor", "Mentor"), ("mentee", "Mentee"), ("both", "Both")],
                max_length=10,
                null=True,
                verbose_name="Desired Role",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="stem",
            field=models.CharField(
                blank=True,
                help_text="Select your STEM interests, separated by commas.",
                max_length=200,
                null=True,
                verbose_name="STEM",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="stem_other",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Other STEM"
            ),
        ),
    ]
