# Generated by Django 4.2.16 on 2025-01-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_profile_learn_remove_profile_question_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="area_of_interest",
        ),
    ]
