# Generated by Django 4.2.16 on 2025-01-17 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0012_remove_profile_area_of_interest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="athletics",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="athletics_other",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="stem",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="stem_other",
        ),
        migrations.CreateModel(
            name="AreasOfInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "athletics",
                    models.CharField(
                        blank=True,
                        help_text="Select your athletics interests, separated by commas.",
                        max_length=200,
                        null=True,
                        verbose_name="Athletics",
                    ),
                ),
                (
                    "athletics_other",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Other Athletics",
                    ),
                ),
                (
                    "stem",
                    models.CharField(
                        blank=True,
                        help_text="Select your STEM interests, separated by commas.",
                        max_length=200,
                        null=True,
                        verbose_name="STEM",
                    ),
                ),
                (
                    "stem_other",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Other STEM"
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas_of_interest",
                        to="users.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
