# Generated by Django 4.2.16 on 2025-01-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_remove_profile_athletics_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="application_question",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Question"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="ACS_association",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="ACS Association"
            ),
        ),
    ]
