# Generated by Django 4.2.16 on 2025-04-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_profile_application_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="interests",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Interests (single words)",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="interests_embeddings",
            field=models.TextField(
                blank=True, null=True, verbose_name="Interests Embeddings"
            ),
        ),
    ]
