# Generated by Django 4.2.16 on 2025-04-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_profile_interests_profile_interests_embeddings"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cluster_label",
            field=models.IntegerField(
                blank=True, help_text="K-means cluster label", null=True
            ),
        ),
    ]
