# Generated by Django 5.1.1 on 2024-10-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("friend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendlist",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
